### ISSUE TITLE
Graph not generated

### ISSUE THREAD

**Issue by abhijeetnijampurkar** [ranjaykrishna/GraphViz#1]
**Input json file:** 
{
    "url": "https://cs.stanford.edu/people/rak248/VG_100K/61512.jpg",
    "objects": [
        {"name": "horse"},
        {"name": "grass"}
    ],
    "attributes": [
        {"attribute": "brown", "object": 1072844}        
    ],
    "relationships": [
        {"predicate": "IN", "object":1072845 , "subject":1072844 }        
    ]
}

**Output attached:**
![output](https://user-images.githubusercontent.com/45970462/64524355-f9cc3c00-d31b-11e9-8d23-ded46a950ee3.png)

**Comment by bibekyess** [comment]
Hi, Interestingly, I am also facing the same issue on my desktop. But, when I run it on my laptop, there is no issue. But, since I want to run on my desktop, can you please share how did you solve this problem? Thank you!

**Comment by willxxy** [comment]
@abhijeetnijampurkar @bibekyess did you guys get any updates on this? I am running into the same problerm

**Comment by bibekyess** [comment]
Yeah, it is solved. https://github.com/ranjaykrishna/GraphViz/issues/2#issuecomment-1366317116
